# Generated by Django 3.1.7 on 2021-04-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copacity_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='moodRange',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='response',
            name='pintaRange',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='response',
            name='suicideRadio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='response',
            name='yourName',
            field=models.IntegerField(default=0),
        ),
    ]
