# Generated by Django 3.1.7 on 2021-04-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copacity_app', '0003_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='yourName',
            field=models.IntegerField(choices=[(1, 'Jake'), (2, 'Leah'), (3, 'Raizel'), (4, 'Oscar')], default=0),
        ),
    ]
