# Generated by Django 3.1.7 on 2021-06-13 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('copacity_app', '0006_checkin_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('createdBy', models.CharField(max_length=50)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('adminId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CircleMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copacity_app.circle')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circle_invites', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='circle',
            name='members',
            field=models.ManyToManyField(related_name='circle_member', through='copacity_app.CircleMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
