# Generated by Django 3.1.7 on 2021-06-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copacity_app', '0007_auto_20210613_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='goodToday',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='circle',
            name='hardToday',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
