# Generated by Django 3.1.7 on 2021-06-13 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copacity_app', '0008_auto_20210613_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circle',
            name='goodToday',
        ),
        migrations.RemoveField(
            model_name='circle',
            name='hardToday',
        ),
    ]
