# Generated by Django 3.1.7 on 2021-06-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copacity_app', '0009_auto_20210613_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='visibility',
            field=models.IntegerField(choices=[(1, 'monopoly'), (2, 'kids')], default=0),
        ),
    ]
