# Generated by Django 3.1.7 on 2021-06-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copacity_app', '0010_checkin_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='visibility',
            field=models.IntegerField(default=0),
        ),
    ]
