# Generated by Django 3.1.7 on 2021-06-25 16:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('copacity_app', '0012_auto_20210622_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='circle_member', through='copacity_app.CircleMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
