# Generated by Django 3.1.7 on 2021-07-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copacity_app', '0013_auto_20210625_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='actionsExplained',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='thoughtsExplained',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
    ]
